version: '3'
services:

    server:
        container_name: kasaz-coding-challenge-server
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - APP_PORT=4444
            - DB_NAME=kasaz
            - DB_HOST=database
            - DB_PORT=27017
        ports: 
            - "4444:4444"
        command: ["npm","start"]