version: '3'
services:

    server:
        container_name: kasaz-coding-challenge-server.dev
        volumes:
            - "./server:/app"
        ports: 
            - "3333:3333"
        environment:
            - NODE_ENV=development
        command: ["npm","run","dev"]
    
    client:
        container_name: kasaz-coding-challenge-client.dev
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - "./client:/app"
        ports:
            - "8080:8080"
        command: ["npm","run","serve"]