version: '3'
services:

    server:
        container_name: kasaz-coding-challenge-server
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
            - APP_PORT=4444
            - DB_NAME=kasaz
            - DB_HOST=database
            - DB_PORT=27017
        ports: 
            - "4444:4444"
        command: ["npm","start"]
    
    client:
        container_name: kasaz-coding-challenge-client
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        ports:
            - "8080:80"
        command: ["nginx", "-g", "daemon off;"]

    database:
        container_name: kasaz-coding-challenge-database
        restart: always
        image: mongo
        volumes:
            - "./database/init.js:/docker-entrypoint-initdb.d/init.js:ro"
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=kasaz