version: '3'
services:

    server:
        container_name: kasaz-coding-challenge-server.dev
        restart: always
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - "./server:/app"
        ports: 
            - "3333:3333"
        environment:
            - NODE_ENV=development
        command: ["npm","run","dev"]
    
    client:
        container_name: kasaz-coding-challenge-client.dev
        restart: always
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
            - "./client:/app"
        ports:
            - "8080:8080"
        command: ["npm","run","serve"]
    
    database:
        container_name: kasaz-coding-challenge-database.dev
        restart: always
        image: mongo
        volumes:
            - "./database/init.js:/docker-entrypoint-initdb.d/init.js:ro"
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_DATABASE=develop