version: '3'
services:

    server:
        container_name: kasaz-coding-challenge-server
        ports: 
            - "4444:4444"
        environment:
            - NODE_ENV=production
            - APP_PORT=4444
            - DB_NAME=kasaz
            - DB_HOST=database
            - DB_PORT=27017
        
    client:
        container_name: kasaz-coding-challenge-client
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        ports:
            - "8080:80"